spring.application.name=backend

# Configuración de conexión a Supabase
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.qnzbrdnujtfysngmtlqf
spring.datasource.password=DripShoes7770

# Configuración de JPA / Hibernate para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
